<?php

/*
 * Editor server script for DB table usuario
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'usuario', 'cod_usuario' )
	->fields(
		Field::inst( 'usuario' )
			->validator( 'Validate::notEmpty' ),
		Field::inst( 'usuario' ),
		Field::inst( 'usuario' ),
		Field::inst( 'usuario' )
	)
	->process( $_POST )
	->json();

