
/*
 * Editor client script for DB table usuario
 * Automatically generated by http://editor.datatables.net/generator
 */

(function($){

$(document).ready(function() {
	var editor = new $.fn.dataTable.Editor( {
		"ajax": "php/table.usuario.php",
		"table": "#usuario",
		"fields": [
			{
				"label": "cod_usu",
				"name": "usuario",
				"type": "text"
			},
			{
				"label": "nom_usu",
				"name": "usuario",
				"type": "text"
			},
			{
				"label": "pass_usu",
				"name": "usuario",
				"type": "text"
			},
			{
				"label": "nivel_asu",
				"name": "usuario",
				"type": "text"
			}
		]
	} );

	$('#usuario').dataTable( {
		"dom": "Tfrtip",
		"ajax": "php/table.usuario.php",
		"columns": [
			{
				"data": "usuario"
			},
			{
				"data": "usuario"
			},
			{
				"data": "usuario"
			},
			{
				"data": "usuario"
			}
		],
		"tableTools": {
			"sRowSelect": "os",
			"aButtons": [
				{ "sExtends": "editor_create", "editor": editor },
				{ "sExtends": "editor_edit",   "editor": editor },
				{ "sExtends": "editor_remove", "editor": editor }
			]
		}
	} );
} );

}(jQuery));

