
-- 
-- Editor server script for DB table usuario
-- Automatically generated by http://editor.datatables.net/generator
-- 

CREATE TABLE `usuario` (
	`id` int(10) NOT NULL auto_increment,
	`usuario` varchar(255) default NULL,
	`usuario` varchar(255) default NULL,
	`usuario` varchar(255) default NULL,
	`usuario` varchar(255) default NULL,
	PRIMARY KEY  (`id`)
);

