 
 <div class="container">
   <div class="text-center">

	  <div id="fb-root"> 
    </div>
	  <script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/es_ES/sdk.js#xfbml=1&appId=816436198369663&version=v2.0";
	  fjs.parentNode.insertBefore(js, fjs);
	  }(document, 'script', 'facebook-jssdk'));</script>

	   <div class="fb-like" style="padding-bottom:5px;"data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"> 
     </div>
     </div> 
     

 <br>
<hr>

<div class="row">
        <div class="col-md-6">
        <?php $año = date('Y'); ?>
   	    <h5>Instanun © <?php echo $año; ?> </h5> 
   	    </div>
   	    <div class="col-md-6">
   	    <ul class="ulfooter pull-right">
   	    <a href="publicar"><li>Publicar anuncio</li></a>
        <a href="registro"><li>Registrarme</li></a>
   	    <a href="conoce"><li>Conoce mas</li></a>
   	    <a href="acerca"><li>Acerca del servicio</li></a>
   	    <a href="politica"><li>Politica de privacidad</li></a>
   	    </ul>
   	    </div>
</div>

</div>